name=DGUS_Async
version=1.0.0
author=Masih Chatraei
maintainer=Masih Chatraei
sentence=Arduino library for DWIN HMI displays.
paragraph=Lightweight async library for DWIN serial HMI displays with queue system, event callbacks, multi-write and animation support.
category=library
url=https://github.com/masihch/DGUS-Async-Arduino
architectures=*
